WITH ASSI_1_QUES_1 AS (
SELECT
R.REGION,
R.YEAR,
R.PRODUCT,
R.REVENUE_MILLIONS,
CASE WHEN 
TO_DATE(CONCAT_WS('-', R.YEAR, R.MONTH, '01')) BETWEEN PM.VALID_FROM_PERIOD AND PM.VALID_TO_PERIOD
THEN (PM.UNIT_PRICE*R.QUANTITY_SOLD)
END AS COST_OF_PRODUCT,
(R.REVENUE_MILLIONS-COST_OF_PRODUCT) AS NET_REVENUE
FROM "VBI"."DATA_LAKE"."REVENUE" AS R
JOIN "VBI"."DATA_LAKE"."PRODUCT_MASTER" AS PM
ON R.PRODUCT = PM.PRODUCT_CODE
WHERE COST_OF_PRODUCT IS NOT NULL
),
REGION_PRODUCT_NAME AS (
SELECT 
RM.REGION_NAME,
RM.REGION_CODE,
PM.PRODUCT_NAME,
PM.PRODUCT_CODE
FROM "VBI"."DATA_LAKE"."REVENUE" AS R
JOIN "VBI"."DATA_LAKE"."PRODUCT_MASTER" AS PM
ON R.PRODUCT = PM.PRODUCT_CODE
JOIN "VBI"."DATA_LAKE"."REGION_MASTER" AS RM
ON R.REGION = RM.REGION_CODE
GROUP BY RM.REGION_NAME,
RM.REGION_CODE,
PM.PRODUCT_NAME,
PM.PRODUCT_CODE
)
SELECT
RPN.REGION_NAME,
RPN.PRODUCT_NAME,
A1Q1.YEAR,
SUM(REVENUE_MILLIONS) AS REVENUE,
SUM(COST_OF_PRODUCT) AS COST_OF_PRODUCT,
SUM(NET_REVENUE) AS NET_REVENUE
FROM ASSI_1_QUES_1 AS A1Q1
JOIN REGION_PRODUCT_NAME AS RPN
ON A1Q1.REGION = RPN.REGION_CODE
AND A1Q1.PRODUCT = RPN.PRODUCT_CODE
GROUP BY A1Q1.YEAR, RPN.REGION_NAME,
RPN.PRODUCT_NAME;