WITH ASSI_1_QUES_1 AS (
SELECT
R.REGION,
R.YEAR,
R.MONTH,
R.PRODUCT,
R.REVENUE_MILLIONS,
(R.REVENUE_MILLIONS/R.QUANTITY_SOLD) AS AVG_SELL_PRICE,
AVG((R.REVENUE_MILLIONS/R.QUANTITY_SOLD)) over(partition by R.MONTH order by R.REGION rows between 6 preceding AND CURRENT ROW) as ROLLING_AVERAGE_SELL_PRICE
FROM "VBI"."DATA_LAKE"."REVENUE" AS R
),
REGION_PRODUCT_NAME AS (
SELECT 
RM.REGION_NAME,
RM.REGION_CODE,
PM.PRODUCT_NAME,
PM.PRODUCT_CODE
FROM "VBI"."DATA_LAKE"."REVENUE" AS R
JOIN "VBI"."DATA_LAKE"."PRODUCT_MASTER" AS PM
ON R.PRODUCT = PM.PRODUCT_CODE
JOIN "VBI"."DATA_LAKE"."REGION_MASTER" AS RM
ON R.REGION = RM.REGION_CODE
GROUP BY RM.REGION_NAME,
RM.REGION_CODE,
PM.PRODUCT_NAME,
PM.PRODUCT_CODE
)
SELECT
RPN.REGION_NAME,
RPN.PRODUCT_NAME,
A1Q1.YEAR,
A1Q1.MONTH,
A1Q1.AVG_SELL_PRICE,
A1Q1.ROLLING_AVERAGE_SELL_PRICE
FROM ASSI_1_QUES_1 AS A1Q1
JOIN REGION_PRODUCT_NAME AS RPN
ON A1Q1.REGION = RPN.REGION_CODE
AND A1Q1.PRODUCT = RPN.PRODUCT_CODE
GROUP BY A1Q1.YEAR, A1Q1.MONTH, RPN.REGION_NAME,
RPN.PRODUCT_NAME, A1Q1.AVG_SELL_PRICE,
A1Q1.ROLLING_AVERAGE_SELL_PRICE;