MERGE INTO "VBI"."REPORTING"."RP_ODR_HEAD_SRC" ROH
USING "VBI"."DATA_LAKE"."ORDER_HEADER_SOURCE" OH
ON ROH.ORDER_NO = OH.ORDER_NO
WHEN MATCHED THEN UPDATE SET ROH."ORDER_NO" = OH."ORDER_NO",
                ROH."ORDER_DATE" = OH."ORDER_DATE",
                ROH."ORDER_TYPE" = OH."ORDER_TYPE", 
                ROH."CUSTOMER_ID" = OH."CUSTOMER_ID",
                ROH."SHIPPING_TYPE" = OH."SHIPPING_TYPE",
                ROH."CREATED_ON" = OH."CREATED_ON",
                ROH."UPDATED_ON" = OH."UPDATED_ON"
WHEN NOT MATCHED THEN INSERT ("ORDER_NO", "ORDER_DATE", "ORDER_TYPE", "CUSTOMER_ID", "SHIPPING_TYPE", "CREATED_ON", "UPDATED_ON")
VALUES (OH."ORDER_NO", OH."ORDER_DATE", OH."ORDER_TYPE", OH."CUSTOMER_ID", OH."SHIPPING_TYPE", OH."CREATED_ON", OH."UPDATED_ON");


MERGE INTO "VBI"."REPORTING"."RP_ODR_ITEM_SRC" ROI
USING "VBI"."DATA_LAKE"."ORDER_ITEM_SOURCE" OI
ON ROI.ORDER_NUMBER = OI.ORDER_NUMBER AND ROI.ITEM_NO = OI.ITEM_NO
WHEN MATCHED THEN UPDATE SET ROI."ORDER_NUMBER" = OI."ORDER_NUMBER",
                             ROI."ITEM_NO" = OI."ITEM_NO",
                             ROI."PRODUCT_ID" = OI."PRODUCT_ID",
                             ROI."QUANTITY" =  OI."QUANTITY",
                             ROI."PRICE" = OI."PRICE",
                             ROI."CREATED_ON" = OI."CREATED_ON",
                             ROI."UPDATED_ON" = OI."UPDATED_ON"
WHEN NOT MATCHED THEN INSERT ("ORDER_NUMBER", "ITEM_NO", "PRODUCT_ID", "QUANTITY", "PRICE", "CREATED_ON", "UPDATED_ON")
VALUES (OI."ORDER_NUMBER", OI."ITEM_NO", OI."PRODUCT_ID", OI."QUANTITY", OI."PRICE", OI."CREATED_ON", OI."UPDATED_ON");

CREATE OR REPLACE STREAM "VBI"."DATA_LAKE"."STREAM_ORDER_HEADER_SOURCE" ON TABLE "VBI"."DATA_LAKE"."ORDER_HEADER_SOURCE";
CREATE OR REPLACE STREAM "VBI"."DATA_LAKE"."STREAM_ORDER_ITEM_SOURCE" ON TABLE "VBI"."DATA_LAKE"."ORDER_ITEM_SOURCE";


CREATE OR REPLACE TASK "VBI"."REPORTING"."TASK_ODR_HEAD_SRC"
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '5 minute'
WHEN
  SYSTEM$STREAM_HAS_DATA('"VBI"."DATA_LAKE"."STREAM_ORDER_HEADER_SOURCE"')
AS
MERGE INTO "VBI"."REPORTING"."RP_ODR_HEAD_SRC" ROH
USING "VBI"."DATA_LAKE"."STREAM_ORDER_HEADER_SOURCE" OH
ON ROH.ORDER_NO = OH.ORDER_NO
WHEN MATCHED THEN UPDATE SET ROH."ORDER_NO" = OH."ORDER_NO",
                              ROH."ORDER_DATE" = OH."ORDER_DATE",
                              ROH."ORDER_TYPE" = OH."ORDER_TYPE", 
                              ROH."CUSTOMER_ID" = OH."CUSTOMER_ID",
                              ROH."SHIPPING_TYPE" = OH."SHIPPING_TYPE",
                              ROH."CREATED_ON" = OH."CREATED_ON",
                              ROH."UPDATED_ON" = OH."UPDATED_ON"
WHEN NOT MATCHED THEN INSERT ("ORDER_NO", "ORDER_DATE", "ORDER_TYPE", "CUSTOMER_ID", "SHIPPING_TYPE", "CREATED_ON", "UPDATED_ON")
VALUES (OH."ORDER_NO", OH."ORDER_DATE", OH."ORDER_TYPE", OH."CUSTOMER_ID", OH."SHIPPING_TYPE", OH."CREATED_ON", OH."UPDATED_ON");


CREATE OR REPLACE TASK "VBI"."REPORTING"."TASK_ODR_ITEM_SRC"
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '5 minute'
WHEN
  SYSTEM$STREAM_HAS_DATA('"VBI"."DATA_LAKE"."STREAM_ORDER_ITEM_SOURCE"')
AS
MERGE INTO "VBI"."REPORTING"."RP_ODR_ITEM_SRC" ROI
USING "VBI"."DATA_LAKE"."STREAM_ORDER_ITEM_SOURCE" OI
ON ROI.ORDER_NUMBER = OI.ORDER_NUMBER AND ROI.ITEM_NO = OI.ITEM_NO
WHEN MATCHED THEN UPDATE SET ROI."ORDER_NUMBER" = OI."ORDER_NUMBER",
                             ROI."ITEM_NO" = OI."ITEM_NO",
                             ROI."PRODUCT_ID" = OI."PRODUCT_ID",
                             ROI."QUANTITY" =  OI."QUANTITY",
                             ROI."PRICE" = OI."PRICE",
                             ROI."CREATED_ON" = OI."CREATED_ON",
                             ROI."UPDATED_ON" = OI."UPDATED_ON"
WHEN NOT MATCHED THEN INSERT ("ORDER_NUMBER", "ITEM_NO", "PRODUCT_ID", "QUANTITY", "PRICE", "CREATED_ON", "UPDATED_ON")
VALUES (OI."ORDER_NUMBER", OI."ITEM_NO", OI."PRODUCT_ID", OI."QUANTITY", OI."PRICE", OI."CREATED_ON", OI."UPDATED_ON");


ALTER TASK "VBI"."REPORTING"."TASK_ODR_ITEM_SRC" RESUME;
ALTER TASK "VBI"."REPORTING"."TASK_ODR_HEAD_SRC" RESUME;


CREATE OR REPLACE VIEW "VBI"."REPORTING"."VW_ODR_HEAD_ITEM_SRC" AS
SELECT 
ROH."ORDER_NO",
ROH."ORDER_DATE",
ROH."ORDER_TYPE",
ROH."CUSTOMER_ID",
ROH."SHIPPING_TYPE",
ROI."ITEM_NO",
ROI."PRODUCT_ID",
ROI."QUANTITY",
ROI."PRICE",
ROH."CREATED_ON",
ROH."UPDATED_ON"
FROM "VBI"."REPORTING"."RP_ODR_HEAD_SRC" AS ROH
JOIN "VBI"."REPORTING"."RP_ODR_ITEM_SRC" AS ROI
ON ROH.ORDER_NO = ROI.ORDER_NUMBER;






