WITH ASSI_1_QUES_4 AS (
SELECT
R.REGION,
R.YEAR,
R.PRODUCT,
MAX(R.REVENUE_MILLIONS) AS REVENUE
FROM "VBI"."DATA_LAKE"."REVENUE" AS R
GROUP BY R.REGION, R.YEAR, R.PRODUCT
),
REGION_PRODUCT_NAME AS (
SELECT 
RM.REGION_NAME,
RM.REGION_CODE,
PM.PRODUCT_NAME,
PM.PRODUCT_CODE
FROM "VBI"."DATA_LAKE"."REVENUE" AS R
JOIN "VBI"."DATA_LAKE"."PRODUCT_MASTER" AS PM
ON R.PRODUCT = PM.PRODUCT_CODE
JOIN "VBI"."DATA_LAKE"."REGION_MASTER" AS RM
ON R.REGION = RM.REGION_CODE
GROUP BY RM.REGION_NAME,
RM.REGION_CODE,
PM.PRODUCT_NAME,
PM.PRODUCT_CODE
)
SELECT
RPN.REGION_NAME,
RPN.PRODUCT_NAME,
A1Q1.YEAR,
REVENUE
FROM ASSI_1_QUES_4 AS A1Q1
JOIN REGION_PRODUCT_NAME AS RPN
ON A1Q1.REGION = RPN.REGION_CODE
AND A1Q1.PRODUCT = RPN.PRODUCT_CODE;



